version: '3.8'
services:
  # nestapi:
  #   container_name: minimalist-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3333:3333
  #   depends_on:
  #     postgresdb:
  #       condition: service_healthy
  #   restart: on-failure

  # postgresdb:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=myuser
  #     - POSTGRES_PASSWORD=mypassword
  #     - POSTGRES_DB=mydb
  #   volumes:
  #     - postgres:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
  #   healthcheck:
  #     test: ['CMD-SHELL', 'pg_isready', '-d', 'mydb']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  test-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5434:5434'

volumes:
  postgres: