version: '3.8'
services:
  nest-api:
    container_name: nest-api-sun
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333

  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:

networks:
  nestjs-crud:
