version: '3.8'
services:
  postgresdb:
    image: postgres:13.5
    container_name: postgresdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - postgres-network

  nest-api:
    container_name: nest-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    networks:
      - postgres-network

volumes:
  postgres:

networks:
  postgres-network:
